"""set uniqconstraint for ingredients

Revision ID: d9a34afa8f60
Revises: 030d28515470
Create Date: 2025-03-26 12:29:20.280433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a34afa8f60'
down_revision: Union[str, None] = '030d28515470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ingredient_measurement', 'ingredients', ['name', 'measurement_unit'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ingredient_measurement', 'ingredients', type_='unique')
    # ### end Alembic commands ###
