"""set new relationships

Revision ID: 030d28515470
Revises: 0c04b30cdf3b
Create Date: 2025-03-26 12:21:11.753933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030d28515470'
down_revision: Union[str, None] = '0c04b30cdf3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amount_ingredients', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index('ix_ingr_shop_cart_ingredient_id', 'amount_ingredients', ['ingredient_id'], unique=False)
    op.create_index('ix_ingr_shop_cart_shopping_list_id', 'amount_ingredients', ['shopping_list_id'], unique=False)
    op.create_unique_constraint('uq_ingr_shop_cart', 'amount_ingredients', ['ingredient_id', 'shopping_list_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ingr_shop_cart', 'amount_ingredients', type_='unique')
    op.drop_index('ix_ingr_shop_cart_shopping_list_id', table_name='amount_ingredients')
    op.drop_index('ix_ingr_shop_cart_ingredient_id', table_name='amount_ingredients')
    op.alter_column('amount_ingredients', 'amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
